# helm install harbor -n kube-system -f ./values.yaml harbor/harbor
expose:
  type: nodePort   
  tls:
    enabled: false
externalURL: http://172.27.0.3:30002
harborAdminPassword: "Harbor12345"
persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      storageClass: "local-path"
      accessMode: ReadWriteOnce
      size: 20Gi
    chartmuseum:
      storageClass: "local-path"
      accessMode: ReadWriteOnce
      size: 5Gi
    jobservice:
      storageClass: "local-path"
      accessMode: ReadWriteOnce
      size: 5Gi
    database:
      storageClass: "local-path"
      accessMode: ReadWriteOnce
      size: 5Gi
    redis:
      storageClass: "local-path"
      accessMode: ReadWriteOnce
      size: 5Gi
    trivy:
      storageClass: "local-path"
      accessMode: ReadWriteOnce
      size: 5Gi
  imageChartStorage:
    type: s3
    s3:
      bucket: harbor
      accesskey: minioadmin
      secretkey: minioadmin
      regionendpoint: http://172.27.0.3:9000
      secure: false
      rootdirectory: /
metrics:
  enabled: true
  core:
    path: /metrics
    port: 8001
  registry:
    path: /metrics
    port: 8001
  jobservice:
    path: /metrics
    port: 8001
  exporter:
    path: /metrics
    port: 8001



#[root@node1 ~]# cat /etc/docker/daemon.json 
#{
#    "insecure-registries": ["172.27.0.3:30002"]
#}

#如果忘记密码可以通过以下命令查看.
#echo $(cat /root/.docker/config.json | grep "auth" |awk 'NR==2{print $2}'| cut -d '"' -f2) | base64 -d
